
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.ShippingAdmin
{
		///
		///	Properties of a shipping carrier-specific setting associated with a carrier configuration.
		///
		public class Setting
		{
			public AuditInfo AuditInfo { get; set; }

			public string Key { get; set; }

			public LocalizableString Label { get; set; }

			public string Value { get; set; }

		}

}