
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace Mozu.Api.Contracts.PaymentService.Extensibility.V1
{
		public class GatewayCaptureResponse
		{
			public string AuthCode { get; set; }

			public string AvsCodes { get; set; }

			public decimal CapturedAmount { get; set; }

			public string CvV2Codes { get; set; }

			public bool IsDeclined { get; set; }

			public ConnectionStatuses RemoteConnectionStatus { get; set; }

			public string ResponseCode { get; set; }

			public List<KeyValueTuple> ResponseData { get; set; }

			public string ResponseText { get; set; }

			public string TransactionId { get; set; }

		}

}