
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.Content
{
		///
		///	The list of document types and related properties that define content used by the content management system (CMS).
		///
		public class DocumentList
		{
			public string DocumentListType { get; set; }

			public List<string> DocumentTypes { get; set; }

			public bool? EnableActiveDateRanges { get; set; }

			public bool? EnablePublishing { get; set; }

			public string ListFQN { get; set; }

			public JObject Metadata { get; set; }

			public string Name { get; set; }

			public string Namespace { get; set; }

			public int? ScopeId { get; set; }

			public string ScopeType { get; set; }

			public string Security { get; set; }

			public bool? SupportsActiveDateRanges { get; set; }

			public bool? SupportsPublishing { get; set; }

			public List<string> Usages { get; set; }

			public List<View> Views { get; set; }

		}

}