
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Security;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using System.Threading;

namespace Mozu.Api.Resources.Commerce.Catalog.Admin.Couponsets
{
	/// <summary>
	/// 
	/// </summary>
	public partial class AssignedDiscountResource  	{
		///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly IApiContext _apiContext;

		
		public AssignedDiscountResource(IApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		public AssignedDiscountResource CloneWithApiContext(Action<IApiContext> contextModification) 
		{
			return new AssignedDiscountResource(_apiContext.CloneWith(contextModification));
		}

				

		/// <summary>
		/// 
		/// </summary>
		/// <param name="couponSetCode"></param>
		/// <returns>
		/// List{<see cref="Mozu.Api.Contracts.ProductAdmin.AssignedDiscount"/>}
		/// </returns>
		/// <example>
		/// <code>
		///   var assigneddiscount = new AssignedDiscount();
		///   var assignedDiscount = await assigneddiscount.GetAssignedDiscountsAsync( couponSetCode);
		/// </code>
		/// </example>
		public virtual async Task<List<Mozu.Api.Contracts.ProductAdmin.AssignedDiscount>> GetAssignedDiscountsAsync(string couponSetCode, CancellationToken ct = default(CancellationToken))
		{
			MozuClient<List<Mozu.Api.Contracts.ProductAdmin.AssignedDiscount>> response;
			var client = Mozu.Api.Clients.Commerce.Catalog.Admin.Couponsets.AssignedDiscountClient.GetAssignedDiscountsClient( couponSetCode);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync(ct).ConfigureAwait(false);
			return await response.ResultAsync();

		}


		/// <summary>
		/// 
		/// </summary>
		/// <param name="couponSetCode"></param>
		/// <param name="assignedDiscount"></param>
		/// <returns>
		/// <see cref="System.IO.Stream"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var assigneddiscount = new AssignedDiscount();
		///   var stream = await assigneddiscount.AssignDiscountAsync( assignedDiscount,  couponSetCode);
		/// </code>
		/// </example>
		public virtual async Task<System.IO.Stream> AssignDiscountAsync(Mozu.Api.Contracts.ProductAdmin.AssignedDiscount assignedDiscount, string couponSetCode, CancellationToken ct = default(CancellationToken))
		{
			MozuClient<System.IO.Stream> response;
			var client = Mozu.Api.Clients.Commerce.Catalog.Admin.Couponsets.AssignedDiscountClient.AssignDiscountClient( assignedDiscount,  couponSetCode);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync(ct).ConfigureAwait(false);
			return await response.ResultAsync();

		}


		/// <summary>
		/// 
		/// </summary>
		/// <param name="couponSetCode"></param>
		/// <param name="discountId"></param>
		/// <returns>
		/// <see cref="System.IO.Stream"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var assigneddiscount = new AssignedDiscount();
		///   var stream = await assigneddiscount.UnAssignDiscountAsync( couponSetCode,  discountId);
		/// </code>
		/// </example>
		public virtual async Task<System.IO.Stream> UnAssignDiscountAsync(string couponSetCode, int discountId, CancellationToken ct = default(CancellationToken))
		{
			MozuClient<System.IO.Stream> response;
			var client = Mozu.Api.Clients.Commerce.Catalog.Admin.Couponsets.AssignedDiscountClient.UnAssignDiscountClient( couponSetCode,  discountId);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync(ct).ConfigureAwait(false);
			return await response.ResultAsync();

		}


	}

}


