
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Urls.Commerce.Checkouts
{
	public partial class PaymentUrl 
	{

				/// <summary>
        /// Get Resource Url for PerformPaymentAction
        /// </summary>
        /// <param name="checkoutId"></param>
        /// <param name="paymentId">Unique identifier of the payment for which to perform the action.</param>
        /// <param name="responseFields">Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl PerformPaymentActionUrl(string checkoutId, string paymentId, string responseFields =  null)
		{
			var url = "/api/commerce/checkouts/{checkoutId}/payments/{paymentId}/actions?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "checkoutId", checkoutId);
			mozuUrl.FormatUrl( "paymentId", paymentId);
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for CreatePaymentAction
        /// </summary>
        /// <param name="checkoutId"></param>
        /// <param name="responseFields">Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CreatePaymentActionUrl(string checkoutId, string responseFields =  null)
		{
			var url = "/api/commerce/checkouts/{checkoutId}/payments/actions?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "checkoutId", checkoutId);
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

						
	}
}

