
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Security;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using System.Threading;

namespace Mozu.Api.Resources.Commerce.Payments
{
	/// <summary>
	/// commerce/payments/tokens related resources. DOCUMENT_HERE 
	/// </summary>
	public partial class PublicTokenResource  	{
		///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly IApiContext _apiContext;

		
		public PublicTokenResource(IApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		public PublicTokenResource CloneWithApiContext(Action<IApiContext> contextModification) 
		{
			return new PublicTokenResource(_apiContext.CloneWith(contextModification));
		}

				

		/// <summary>
		/// 
		/// </summary>
		/// <param name="responseFields">Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.</param>
		/// <param name="request"></param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.PaymentService.Response.TokenResponse"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var publictoken = new PublicToken();
		///   var tokenResponse = await publictoken.CreateAsync( request,  responseFields);
		/// </code>
		/// </example>
		public virtual async Task<Mozu.Api.Contracts.PaymentService.Response.TokenResponse> CreateAsync(Mozu.Api.Contracts.PaymentService.PublicToken request, string responseFields =  null, CancellationToken ct = default(CancellationToken))
		{
			MozuClient<Mozu.Api.Contracts.PaymentService.Response.TokenResponse> response;
			var client = Mozu.Api.Clients.Commerce.Payments.PublicTokenClient.CreateClient( request,  responseFields);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync(ct).ConfigureAwait(false);
			return await response.ResultAsync();

		}


		/// <summary>
		/// 
		/// </summary>
		/// <param name="cardType"></param>
		/// <param name="responseFields">Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.</param>
		/// <param name="request"></param>
		/// <returns>
		/// JObject
		/// </returns>
		/// <example>
		/// <code>
		///   var publictoken = new PublicToken();
		///   var json = await publictoken.ExecuteAsync( request,  cardType,  responseFields);
		/// </code>
		/// </example>
		public virtual async Task<JObject> ExecuteAsync(Mozu.Api.Contracts.PaymentService.Request.ExecuteRequest request, string cardType, string responseFields =  null, CancellationToken ct = default(CancellationToken))
		{
			MozuClient<JObject> response;
			var client = Mozu.Api.Clients.Commerce.Payments.PublicTokenClient.ExecuteClient( request,  cardType,  responseFields);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync(ct).ConfigureAwait(false);
			return await response.ResultAsync();

		}


	}

}


