
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.ShippingRuntime
{
		///
		///	Properties of an item for which to calculate a shipping rate.
		///
		public class RateRequestItem
		{
			public JObject Data { get; set; }

			public string ItemId { get; set; }

			public List<ProductSummary> ProductSummaries { get; set; }

			public int? Quantity { get; set; }

			public bool? ShipsByItself { get; set; }

			public ItemMeasurements UnitMeasurements { get; set; }

		}

}