
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace Mozu.Api.Contracts.ShippingRuntime
{
		public class RateRequestAttribute
		{
			public int? AttributeDefinitionId { get; set; }

			public string FullyQualifiedName { get; set; }

			public List<object> Values { get; set; }

		}

}