
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.Customer
{
		///
		///	Contact information, including the contact's name, address, phone numbers, email addresses, and company (if supplied). Also indicates whether this is a billing, shipping, or billing and shipping contact.
		///
		public class CustomerContact
		{
			public int AccountId { get; set; }

			public Address Address { get; set; }

			public AuditInfo AuditInfo { get; set; }

			public string CompanyOrOrganization { get; set; }

			public string Email { get; set; }

			///
			///The fax number associated with the customer account.
			///
			public string FaxNumber { get; set; }

			public string FirstName { get; set; }

			public int Id { get; set; }

			///
			///Descriptive text used as a label for objects, such as field names, facets, date ranges, contact information, and package information.
			///
			public string Label { get; set; }

			public string LastNameOrSurname { get; set; }

			public string MiddleNameOrInitial { get; set; }

			public Phone PhoneNumbers { get; set; }

			///
			///List of the types associated with a customer contact, such as Billing or Fulfillment.
			///
			public List<ContactType> Types { get; set; }

		}

}