
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.CommerceRuntime.Commerce
{
		///
		///	Mozu.CommerceRuntime.Contracts.Commerce.ThresholdMessage ApiType DOCUMENT_HERE 
		///
		public class ThresholdMessage
		{
			///
			///The unique identifier of the discount.
			///
			public int DiscountId { get; set; }

			///
			///The text of the change message, such as "This product is no longer available." System-supplied and read-only.
			///
			public string Message { get; set; }

			///
			///requiresCouponCode ApiType DOCUMENT_HERE 
			///
			public bool RequiresCouponCode { get; set; }

			///
			///showInCart ApiType DOCUMENT_HERE 
			///
			public bool ShowInCart { get; set; }

			///
			///showOnCheckout ApiType DOCUMENT_HERE 
			///
			public bool ShowOnCheckout { get; set; }

			///
			///thresholdValue ApiType DOCUMENT_HERE 
			///
			public decimal ThresholdValue { get; set; }

		}

}