
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.Reference
{
		///
		///	A world date and time standard such as "Dateline Standard Time" or "UTC-12".
		///
		public class TimeZone
		{
			public string Id { get; set; }

			public bool IsDaylightSavingsTime { get; set; }

			public double Offset { get; set; }

		}

}