
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace Mozu.Api.Contracts.Reference
{
		///
		///	The paged collection of all units of measure that the system currently supports.
		///
		public class UnitOfMeasureCollection
		{
			public List<UnitOfMeasure> Items { get; set; }

			public int TotalCount { get; set; }

		}

}