
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Urls.Commerce.Catalog.Admin
{
	public partial class CurrencyLocalizationUrl 
	{

		/// <summary>
        /// Get Resource Url for GetCurrencyLocalizations
        /// </summary>
        /// <param name="responseFields"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetCurrencyLocalizationsUrl(string responseFields =  null)
		{
			var url = "/api/commerce/catalog/admin/currency/?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for GetCurrencyExchangeRate
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <param name="responseFields"></param>
        /// <param name="toCurrencyCode"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetCurrencyExchangeRateUrl(string currencyCode, string toCurrencyCode, string responseFields =  null)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}/exchangerates/{toCurrencyCode}?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			mozuUrl.FormatUrl( "responseFields", responseFields);
			mozuUrl.FormatUrl( "toCurrencyCode", toCurrencyCode);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for GetCurrencyExchangeRates
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <param name="responseFields"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetCurrencyExchangeRatesUrl(string currencyCode, string responseFields =  null)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}/exchangerates?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for GetCurrencyLocalization
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <param name="responseFields"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetCurrencyLocalizationUrl(string currencyCode, string responseFields =  null)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

				/// <summary>
        /// Get Resource Url for AddCurrencyLocalization
        /// </summary>
        /// <param name="responseFields"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl AddCurrencyLocalizationUrl(string responseFields =  null)
		{
			var url = "/api/commerce/catalog/admin/currency/?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for AddCurrencyExchangeRates
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl AddCurrencyExchangeRatesUrl(string currencyCode)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}/exchangerates";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			return mozuUrl;
		}

				/// <summary>
        /// Get Resource Url for UpdateCurrencyExchangeRates
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateCurrencyExchangeRatesUrl(string currencyCode)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}/exchangerates";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for UpdateCurrencyLocalization
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <param name="responseFields"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateCurrencyLocalizationUrl(string currencyCode, string responseFields =  null)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}?responseFields={responseFields}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			mozuUrl.FormatUrl( "responseFields", responseFields);
			return mozuUrl;
		}

				/// <summary>
        /// Get Resource Url for DeleteCurrencyLocalization
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl DeleteCurrencyLocalizationUrl(string currencyCode)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			return mozuUrl;
		}

		/// <summary>
        /// Get Resource Url for DeleteCurrencyExchangeRate
        /// </summary>
        /// <param name="currencyCode"></param>
        /// <param name="toCurrencyCode"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl DeleteCurrencyExchangeRateUrl(string currencyCode, string toCurrencyCode)
		{
			var url = "/api/commerce/catalog/admin/currency/{currencyCode}/exchangerates/{toCurrencyCode}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "currencyCode", currencyCode);
			mozuUrl.FormatUrl( "toCurrencyCode", toCurrencyCode);
			return mozuUrl;
		}

		
	}
}

