
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.ProductAdmin
{
		///
		///	Properties of a component product in a product bundle. A product bundle can represent either a collection of multiple products sold as a single entity, or a collection of the same product sold as a package. For example, a 10-pack of socks.
		///
		public class BundledProduct
		{
			///
			///Indicates the fulfillment types that the product supports.
			///
			public List<string> FulfillmentTypesSupported { get; set; }

			///
			///Height of the bundle package in imperial units of feet and inches.
			///
			public Measurement PackageHeight { get; set; }

			///
			///Length of the bundle package in imperial units of feet and inches.
			///
			public Measurement PackageLength { get; set; }

			///
			///Weight of the bundle package in imperial units of pounds and ounces.
			///
			public Measurement PackageWeight { get; set; }

			///
			///Width of the bundle package in imperial units of feet and inches.
			///
			public Measurement PackageWidth { get; set; }

			///
			///The price of the bundled product set for the tenant.
			///
			public ProductPrice Price { get; set; }

			///
			///Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
			///
			public string ProductCode { get; set; }

			///
			///The read-only name of the component in a bundled product.
			///
			public string ProductName { get; set; }

			///
			///The quantity of an individual component product in a bundle. For example, if a product bundle represents a 10-pack of socks, the quantity value for the bundled product would be 10.
			///
			public int Quantity { get; set; }

		}

}