
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.ProductAdmin
{
		///
		///	Mozu.ProductAdmin.Contracts.CategorySequence ApiType DOCUMENT_HERE 
		///
		public class CategorySequence
		{
			///
			///Unique identifier of a category. 
			///
			public int CategoryId { get; set; }

			///
			///Mozu.ProductAdmin.Contracts.CategorySequence parentCategoryId ApiTypeMember DOCUMENT_HERE 
			///
			public int? ParentCategoryId { get; set; }

			///
			///The numeric order of objects, used by a vocabulary value defined for an extensible attribute, images, and categories.
			///
			public int Sequence { get; set; }

		}

}