
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace Mozu.Api.Contracts.ProductAdmin
{
		///
		///	Properties of a defined value for a product extra attribute.
		///
		public class ProductExtraValue
		{
			public AttributeVocabularyValue AttributeVocabularyValueDetail { get; set; }

			public ProductExtraValueDeltaPrice DeltaPrice { get; set; }

			public decimal? DeltaWeight { get; set; }

			public bool? IsDefaulted { get; set; }

			public List<ProductExtraValueDeltaPrice> LocalizedDeltaPrice { get; set; }

			///
			///When setting up the extra on a parent product, you can specify a quantity. You can have an extra that is a quantity > 1 of another product.
			///
			public int? Quantity { get; set; }

			public object Value { get; set; }

		}

}