
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.ProductAdmin
{
		///
		///	Mozu.ProductRuntime.Contracts.ProductSortExpression ApiType DOCUMENT_HERE 
		///
		public class ProductSortExpression
		{
			///
			///ASC or DESC. Represents a product that is positioned out of its normal sort position. It can be boosted to the top of the list, positioned exactly or buried at the bottom.
			///
			public string Direction { get; set; }

			///
			///The name of the field to sort on. A known sort field or sortable attribute.
			///
			public string Field { get; set; }

		}

}