
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace Mozu.Api.Contracts.ProductAdmin
{
		public class SiteSearchSettings
		{
			public List<string> CustomBoosts { get; set; }

			public List<SiteSearchRelevancyCustomField> CustomFields { get; set; }

			public bool IsDefault { get; set; }

			public int? MinimumMatchPercent { get; set; }

			public string SettingsName { get; set; }

			public SiteSearchKeywordRelevancySettings SiteKeywordRelevancy { get; set; }

			public SiteSearchPhraseRelevancySettings SitePhraseRelevancy { get; set; }

		}

}